import argparse as ap
import utils
from transformers import pipeline


def summarize_pipeline(text, summarizer, min_length, max_length):
    """
    Args:
        text (dtr): text to be summarized
        summarizer (pipeline object): pipeline object for summarization
        min_length (int): minimum length of summary
        max_length (int): maximum length of summary

    Returns:
        list: list containing summary text
    """
    # forward pass
    summarized_text = summarizer(text, min_length=min_length,
                                 max_length=max_length, truncation=True)
    return summarized_text


def parse_arguments():
    parser = ap.ArgumentParser(description=utils.descriptions["summarize"])

    parser.add_argument('text', metavar='input_text',
                        type=str,
                        help='input text to be summarized')

    parser.add_argument('--min_len',
                        type=int,
                        help='minimum length of summarized text')

    parser.add_argument('--max_len',
                        type=int,
                        help='maximum length of summarized text')

    parser.add_argument('--verbose',
                        type=bool,
                        help='returns all warnings generated by the program')
    parser.add_argument('--demo',
                        type=bool,
                        default=False)
    parser.add_argument('--model',
                        type=str,
                        default="t5-small",
                        help="model that you want your summirzation to use (default t5-small)") # noqa
    args = parser.parse_args()
    return args


def main():
    min_length = 20
    max_length = 70
    verbose_op = False
    args = parse_arguments()
    model = args.model
    model = model.lower()

    if(args.verbose):
        verbose_op = True

    if(args.min_len):
        min_length = args.min_len
    if(args.max_len):
        max_length = args.max_len

    # Calling it globally so we only have to call it once
    if(not verbose_op):
        import warnings
        warnings.filterwarnings('ignore')

    if((max_length <= min_length) or (max_length - min_length) < 30):
        print("length mismatch! please ensure that max length is at least 30 words \
            greater than max length for a meaningful result and try again!")
        exit(1)

    # Validate URL
    if (utils.check_url(args.text)):
        text_ip = utils.read_url(args.text)
    else:
        text_ip = utils.read_file(args.text, demo=args.demo)

    models = ["t5-base", "t5-small", "bart", "t5-large"]
    if model not in models:
        print(f"{model} is not a valid model. Please ensure model is one of {models}") # noqa : E501
        exit(1)
    if (model == "bart"):
        model = "sshleifer/distilbart-cnn-12-6"

    summarizer = pipeline("summarization", model=model, framework="pt") # noqa : E501

    summarized_text = summarize_pipeline(text_ip, summarizer=summarizer,
                                         min_length=min_length,
                                         max_length=max_length)
    if(verbose_op):
        print(f"Summary of {args.text} between {min_length} and \
                {max_length} words below:\n")
    sentences = utils.format_text(summarized_text[0]['summary_text'])
    for sent in sentences:
        print(sent)


if __name__ == "__main__":
    main()
